## The Notebook as a calculator

In [4]:
5*4+4739-5839/48423920
# shortcut key for compiling: shift+enter

4758.999879419097

In [ ]:
56*83749-372+4829

4694401

In [ ]:
475828338*283741/372823*462382

167444397186505.22

In [ ]:
3**3
# this is 3 to the power of 3

27

## The Notebook as a printer

In [8]:
'My name is Marco'

'My name is Marco'

In [7]:
print('My name is Marco and I am 24 years old 1')

print('My name is Marco and I am',24,'years old 2')
# the print command prints a phrase

My name is Marco and I am 24 years old 1
My name is Marco and I am 24 years old 2


## Programming basics

### 1) Variables: how to store data in python

A variable is a symbol which stores a number or a string. 
The syntax is variable_name = value. You can choose as variable_name whatever you want (more or less...). You can think about variable as the x or the y in maths.

In [10]:
#An example

# variable_name : x
# value : 23

x = 23

force = 48
speed = 4949
electrical_field = 4829

my_name = 'marco'
university_name = 'unimi'

From now on the variable x will contain the value 23. If we type x in the cell and run it we will get as output the value stored in the variable (the same with print())

In [11]:
x

23

In [ ]:
print(x)

23


In [12]:
# Another example

age = 24
name = 'Marco'

print('My name is',name,'and I am',age,'years old')

My name is Marco and I am 24 years old


In [ ]:
dhcdhc

NameError: ignored

You can operate on variable as they are numbers

In [ ]:
# Example 1

#Data
mass = 50
acceleration = 100

#Solution
force = mass*acceleration # 50*100
print(force)



5000


In [13]:
# Example 2
#Data
weight = 92.6 #kg
height = 1.84 #m

#Solution
BMI = weight/height**2 # 92.6/(1.84*1.84)

print(BMI)

27.35113421550094


Now we have seen how to write single numbers and how to do some basic operations (more or less we are at the point like having simply paper and a pencil to do some basic calculation). However we want to learn how to treat big data. So the first question is: How can we store multiple numbers or strings in python?

### 2) Lists: how to store multiple values in python

List are a particular types of variables which can store multiple data. The syntax is list_name = [data1, data2,data3]

In [14]:
# Examples of list declaration

# list_name : ages
# list_content: [23,29,25,26,28]

ages = [23,29,25,26,28]

print(ages)

[23, 29, 25, 26, 28]


In [ ]:
# list_name : names
# list_content: ['Marco','Anna','Giulia','Matteo','Simona']

names = ['Marco','Anna','Giulia','Matteo','Simona']

print('Our friends names:',names)

Names: ['Marco', 'Anna', 'Giulia', 'Matteo', 'Simona']


It is also possible to mix string and numbers

In [15]:
mixed_list = [23,'Marco','Giulia',37328,'Simone']
print(mixed_list)

[23, 'Marco', 'Giulia', 37328, 'Simone']


We can check how long is a list:

In [16]:
list_1 = [27,2738,28329,2839,38348,3837,2636]
list_2 = [27,2738,28329,2839,38348,3837,2636,478,4739,28190]
list_3 = ['hi','how are you','ciao','python']

# len() and inside len(list_name)
print(len(list_1))
print(len(list_2))
print(len(list_3))

7
10
4


It is possible to access to a single element of the list. The sintax is: list_name[position_of_the_element]. REMEMBER THAT THE POSITIONS START AT 0!!!!

In [ ]:
colors = ['red','blu','yellow','green','black']

# list_name[element_position]

#how to print the first element of the list colors
print('The first element of colors is:',colors[0])

#how to print the second element of the list colors
print('The second element of colors is:',colors[1])

#how to print the third element of the list colors
print('The third element of colors is:',colors[2])

#how to print the fourth element of the list colors
print('The fourth element of colors is:',colors[3])

#how to print the fifth element of the list colors
print('The fifth element of colors is:',colors[4])

The first element of colors is: red
The second element of colors is: blu
The third element of colors is: yellow
The fourth element of colors is: green
The fifth element of colors is: black


Why are lists useful? Imagine that you are a doctor. You visit some patients and record their weight and height. After that you want to write all the data on your notebook.

In [ ]:
# with variables

weight_patient1 = 57
weight_patient2 = 49
weight_patient3 = 89
weight_patient4 = 78
weight_patient5 = 73
weight_patient6 = 71
weight_patient7 = 63
weight_patient8 = 100
weight_patient9 = 86
weight_patient10 = 95

height_patient1 = 1.65
height_patient2 = 1.56
height_patient3 = 1.89
height_patient4 = 1.80
height_patient5 = 1.67
height_patient6 = 1.85
height_patient7 = 1.60
height_patient8 = 2.02
height_patient9 = 1.83
height_patient10 = 1.89


print('Patient1 weights',weight_patient1,'kg and is',height_patient1,'m high')
print('Patient2 weights',weight_patient2,'kg and is',height_patient2,'m high')
print('Patient3 weights',weight_patient3,'kg and is',height_patient3,'m high')
print('Patient4 weights',weight_patient4,'kg and is',height_patient4,'m high')
print('Patient5 weights',weight_patient5,'kg and is',height_patient5,'m high')
print('Patient6 weights',weight_patient6,'kg and is',height_patient6,'m high')
print('Patient7 weights',weight_patient7,'kg and is',height_patient7,'m high')
print('Patient8 weights',weight_patient8,'kg and is',height_patient8,'m high')
print('Patient9 weights',weight_patient9,'kg and is',height_patient9,'m high')
print('Patient10 weights',weight_patient10,'kg and is',height_patient10,'m high')

Patient1 weights 57 kg and is 1.65 m high
Patient2 weights 49 kg and is 1.56 m high
Patient3 weights 89 kg and is 1.89 m high
Patient4 weights 78 kg and is 1.8 m high
Patient5 weights 73 kg and is 1.67 m high
Patient6 weights 71 kg and is 1.85 m high
Patient7 weights 63 kg and is 1.6 m high
Patient8 weights 100 kg and is 2.02 m high
Patient9 weights 86 kg and is 1.83 m high
Patient10 weights 95 kg and is 1.89 m high


In [ ]:
# with lists
weights = [57,49,89,78,73,71,63,100,86,95] 
heights = [1.65,1.56,1.89,1.80,1.67,1.85,1.60,2.02,1.83,1.89]

print('Patient1 weights',weights[0],'kg and is',heights[0],'m high')
print('Patient2 weights',weights[1],'kg and is',heights[1],'m high')
print('Patient3 weights',weights[2],'kg and is',heights[2],'m high')
print('Patient4 weights',weights[3],'kg and is',heights[3],'m high')
print('Patient5 weights',weights[4],'kg and is',heights[4],'m high')
print('Patient6 weights',weights[5],'kg and is',heights[5],'m high')
print('Patient7 weights',weights[6],'kg and is',heights[6],'m high')
print('Patient8 weights',weights[7],'kg and is',heights[7],'m high')
print('Patient9 weights',weights[8],'kg and is',heights[8],'m high')
print('Patient10 weights',weights[9],'kg and is',heights[9],'m high')

#next we will see a method to avoid also to re-write every time print(bla_bla)

Patient1 weights 57 kg and is 1.65 m high
Patient2 weights 49 kg and is 1.56 m high
Patient3 weights 89 kg and is 1.89 m high
Patient4 weights 78 kg and is 1.8 m high
Patient5 weights 73 kg and is 1.67 m high
Patient6 weights 71 kg and is 1.85 m high
Patient7 weights 63 kg and is 1.6 m high
Patient8 weights 100 kg and is 2.02 m high
Patient9 weights 86 kg and is 1.83 m high
Patient10 weights 95 kg and is 1.89 m high


If you imagine now to have 1000000 patients you will also understand why lists are useful...

#### Some commands for lists

Pyhton provides some useful commands specifically for list. The syntax is: name_list.command_name(input_command1,input_command2...)

In [ ]:
# count() : returns the number of times that a specified element appears in the list.

ages = [21, 22, 23, 22, 24]

count_23 = ages.count(23) #this command will not return the list, but a number
print(count_23)
print(ages.count(23))

count_22 = ages.count(22)
print(count_22)

1
1
2


In [ ]:
# append() : adds an item to the end of the list.

ages = [21, 22, 23, 22, 24]

ages.append(25) #this command will return the list


print(ages)

[21, 22, 23, 22, 24, 25]


In [17]:
# pop() : removes the item at the given index/position
colors_1 = ['red','blu','yellow']
colors_1.pop(0)
print(colors_1)

['blu', 'yellow']


In [18]:
colors_1 = ['red','blu','yellow']
removed_item = colors_1.pop(1)
print(removed_item)
print(colors_1)

blu
['red', 'yellow']


### 2) Numpy: the most famous library to store multiple values in python

Another way to store and do some 'organization operation' on data is the numpy library. What is a library? A library is a collection of commands (or functions or methods) made by someone that we can use for our research. 

Since numpy is an 'external information' we have to ask to our python notebook to collect it. The sintax for asking to the notebook for accessing to an external library is: import library_name as name_we_want_to_give_to_the_library

In [19]:
import numpy 

In [26]:
import numpy as np #np is the common name used by everyone to call numpy

In [ ]:
# np.command_name(input_instruction)

Numpy offers a new type of variable named array. An array is very similar to a list (but it is supported with more useful properties). 

In [21]:
my_array = np.array([1, 2, 3, 4,638,3728,38292,3728,3729])
print(my_array)


my_list = [34782,37893,36282,32934,4637]

my_second_array = np.array(my_list)
print(my_second_array)

[    1     2     3     4   638  3728 38292  3728  3729]
[34782 37893 36282 32934  4637]


In [22]:
my_array

array([    1,     2,     3,     4,   638,  3728, 38292,  3728,  3729])

Arrays have some very useful properties respect to lists:

In [24]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)

print(array1+1)
print(array1-3)
print(array1*2)
print(array1/4)




[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[2 3 4 5]
[-2 -1  0  1]
[2 4 6 8]
[0.25 0.5  0.75 1.  ]


In [23]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]


print(list1/list2)
print(list1*list2)
print(list1-list2)

TypeError: ignored

It is also possible to generate automatically array 

In [25]:
#Example 1) generate an array made by 1 values

ones_array = np.ones(5)
print(ones_array)

ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Example 2) generate an array made by 0 values

zeros_array = np.zeros(5)
print(zeros_array)

zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
#Example 3) generate an array from the number a to number b(non comprised) with step c 
# syntax: np.arange(a, b, c)


array = np.arange(0,20,5)
print(array)

array = np.arange(0,20,2)
print(array)

array = np.arange(0,20,10)
print(array)

[ 0  5 10 15]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0 10]


In [28]:
#Example 4) generate an array from the number a to number b(comprised) of lenght c, which contains equally divided elements
# syntax: np.linspace(a, b, c)

array = np.linspace(0, 20, 5)
print(array)

array_1 = np.linspace(0, 20, 2)
print(array_1)

array_2 = np.linspace(0, 20, 10)
print(array_2)


[ 0.  5. 10. 15. 20.]
[ 0. 20.]
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [ ]:
#Example 5) generate an array of random numbers

# generate random number from a uniform distribution between 0 and 1
random_array = np.random.rand(10)
print(random_array)

# generate random number from a normal distribution with mean 0 and variance 1
random_normal_array = np.random.randn(10)
print(random_normal_array)


#tips
mu = 5
var = 2
random_normal_array_mu_var = mu+np.random.randn(10)*var
print(random_normal_array_mu_var)

#for other random commands: https://numpy.org/doc/1.16/reference/routines.random.html

[0.5133795  0.93665059 0.96081595 0.39470156 0.94601498 0.27920183
 0.81258569 0.2708974  0.32474548 0.79058625]
[-0.04118745  0.04328324  1.55998191 -0.04714795  0.12950681 -0.83479678
  0.21202596  0.87335821 -1.58226555  2.56795012]
[ 9.33453432  7.59071503  7.85187652  5.48236924  2.98461972 11.04715891
  7.34508488  2.7551695   6.37955054  5.39633394]


In [ ]:
# we can access to element of an array in the same way as for lists

random_array = np.random.rand(10)

print(random_array)

print(random_array[0])
print(random_array[1])

[0.50564502 0.35422551 0.47211714 0.71697467 0.78272128 0.10146416
 0.88707843 0.62556437 0.29610872 0.03556434]
0.5056450173137602
0.3542255137894066


#### Some commands for numpy

In [ ]:
# get min and max values from an array

arr = np.arange(0,10,1) 
print(arr)

min_value = np.min(arr)
print('Min value',min_value)

max_value = np.max(arr)
print('Max value',max_value)



[0 1 2 3 4 5 6 7 8 9]
0
9


In [ ]:
# np.mean

arr = np.random.rand(1000000) 
mean = np.mean(arr)
print(mean)

0.5000014851509655


In [ ]:
# np.std

arr = np.random.randn(1000) 
std = np.std(arr)
print(std)



0.9636419498522035


In [ ]:
# np.var

arr = np.random.randn(1000) 
var = np.var(arr)
print(var)

1.039523251115908


In [ ]:
# np.corrcoef
# Pearson correlation coeff: https://en.wikipedia.org/wiki/Pearson_correlation_coefficient

arr1 = np.random.randn(1000) 
arr2 = np.random.randn(1000) 


corrcoef = np.corrcoef(arr1, arr2)
print(corrcoef)

[[ 1.       -0.044503]
 [-0.044503  1.      ]]


### 3) For cycle: how to rapidly access and modify list and array

for is a special command in Python. It allows to create an iterative cycle on elements of a list or on elemets of a numpy array.

The syntax is: 

In [ ]:
for iterator_name in list_name:
    #command on the iterator
    

In practice in each cycle the iterator_name variable assume the value of an element of the list

In [31]:
list_name = [2637,3727,3828,3829]

for element in list_name:
    print(element)   

2637
3727
3828
3829


In [32]:
print(list_name[0])
print(list_name[1])
print(list_name[2])
print(list_name[3])

2637
3727
3828
3829


In [ ]:
# The TAB or the indentation before the command is extremely important
list_name = [2637,3727,3828,3829]

for element in list_name:

print(element)

IndentationError: expected an indented block (485228597.py, line 5)

In [34]:
list_name = [2637,3727,3828,3829]

for element in list_name:
    print(element)   

print('For finished')

2637
3727
3828
3829
For finished


In [ ]:
list_name = [2637,3727,3828,3829]

for element in list_name:
    print(element*2)

5274
7454
7656
7658


In [35]:
array = np.random.rand(1000)

for element in array:
    print(element)

0.0004929947241514299
0.27307272973758323
0.2562698245057652
0.185439556426242
0.6984492632977531
0.403937521030324
0.8438977057217356
0.3497845262124889
0.23449248448931648
0.869556291484865
0.013886098223390375
0.7645676047436928
0.72504261324878
0.09555407696968043
0.6877242393713277
0.682600925630216
0.9059387915988794
0.44897403182279905
0.6294571781917222
0.8018148455632869
0.820056541431543
0.6965571218069851
0.48013018657776085
0.8650452921099894
0.8943295778604422
0.6253387877040124
0.8142196814908915
0.6391897319049864
0.6446665251550986
0.7497770898919078
0.7380247355539004
0.362232995297207
0.47059245709110675
0.029513052888527125
0.27636764632718225
0.3675854705309728
0.8336044814846602
0.836977375920838
0.2520448598851971
0.21690091346816964
0.9716227051088394
0.8956043772422554
0.2749644444369538
0.6834328438338669
0.29103313443611023
0.06140708447418086
0.3303262893773825
0.6906930944562372
0.480551540735878
0.025575367060325038
0.2857153648617805
0.8835775365349884
0.0

We can also access each element of our list or array cycling on the index:

In [36]:
list_name = [2637,3727,3828,3829]

# Instead of doing like that
for element in list_name:
    print(element)
    
print('')
    

# We can do
for i in range(len(list_name)):
    print(i)
    print(list_name[i])

2637
3727
3828
3829

0
2637
1
3727
2
3828
3
3829


In [ ]:
array = np.random.rand(1000)

for index in range(len(array)):
    print(array[index],index)

0.7009396549765015 0
0.1729883544584343 1
0.6458809039452422 2
0.9263457251384898 3
0.8385501642739897 4
0.10402439741876335 5
0.6002911844367732 6
0.08956073895816408 7
0.03886176304293354 8
0.8341636017874066 9
0.9861713955564139 10
0.7770381872744292 11
0.3756633638381134 12
0.7586010894247913 13
0.6929890960891443 14
0.6041703090660245 15
0.8034990569499151 16
0.4191794756023445 17
0.42135887824954266 18
0.4307508872139757 19
0.6255816837646109 20
0.16822621066093624 21
0.4379843154068487 22
0.42985393896501056 23
0.606991682616767 24
0.35066016020203794 25
0.6405189780762391 26
0.5115211818525461 27
0.36225784900863867 28
0.11989026453939688 29
0.37544326398735495 30
0.7215543637518208 31
0.26017446230179986 32
0.5717765375466259 33
0.30851115646936045 34
0.8000877239318482 35
0.6005698903449883 36
0.7798711020320366 37
0.8590607199265688 38
0.47322204563448167 39
0.739486500582132 40
0.572032108566607 41
0.059193103718803264 42
0.6223319604101417 43
0.3433938170164965 44
0.641858

Come back to the doctor example:

In [ ]:
weights = [57,49,89,78,73,71,63,100,86,95] 
heights = [1.65,1.56,1.89,1.80,1.67,1.85,1.60,2.02,1.83,1.89]

print('Patient1 weights',weights[0],'kg and is',heights[0],'m high')
print('Patient2 weights',weights[1],'kg and is',heights[1],'m high')
print('Patient3 weights',weights[2],'kg and is',heights[2],'m high')
print('Patient4 weights',weights[3],'kg and is',heights[3],'m high')
print('Patient5 weights',weights[4],'kg and is',heights[4],'m high')
print('Patient6 weights',weights[5],'kg and is',heights[5],'m high')
print('Patient7 weights',weights[6],'kg and is',heights[6],'m high')
print('Patient8 weights',weights[7],'kg and is',heights[7],'m high')
print('Patient9 weights',weights[8],'kg and is',heights[8],'m high')
print('Patient10 weights',weights[9],'kg and is',heights[9],'m high')

Patient1 weights 57 kg and is 1.65 m high
Patient2 weights 49 kg and is 1.56 m high
Patient3 weights 89 kg and is 1.89 m high
Patient4 weights 78 kg and is 1.8 m high
Patient5 weights 73 kg and is 1.67 m high
Patient6 weights 71 kg and is 1.85 m high
Patient7 weights 63 kg and is 1.6 m high
Patient8 weights 100 kg and is 2.02 m high
Patient9 weights 86 kg and is 1.83 m high
Patient10 weights 95 kg and is 1.89 m high


In [ ]:
weights = [57,49,89,78,73,71,63,100,86,95] 
heights = [1.65,1.56,1.89,1.80,1.67,1.85,1.60,2.02,1.83,1.89]

#the two list have the same lenght so we can cycle on their index to print the record

for i in range(len(weights)):
    print('Patient',i+1,'weights',weights[i],'kg and is',heights[i],'m high')

Patient 1 weights 57 kg and is 1.65 m high
Patient 2 weights 49 kg and is 1.56 m high
Patient 3 weights 89 kg and is 1.89 m high
Patient 4 weights 78 kg and is 1.8 m high
Patient 5 weights 73 kg and is 1.67 m high
Patient 6 weights 71 kg and is 1.85 m high
Patient 7 weights 63 kg and is 1.6 m high
Patient 8 weights 100 kg and is 2.02 m high
Patient 9 weights 86 kg and is 1.83 m high
Patient 10 weights 95 kg and is 1.89 m high


How can we get values of only patients which overweight?

### 4) If condition: how to make condition inside for cycle

Python offers a particular type of varibale named bool. A bool is a value that can be True or False

In [ ]:
bool_1 = True
bool_2 = False


In [ ]:
#We can obtain a bool as an output of a particular operation

print(1<3)
print(1==1)
print(568748<23)

True
True
False


The if conditions check on a bool value and if this value is True it makes a certain operation

In [ ]:
if bool_value:
    #operation

In [39]:
array = np.arange(0,10,1)

# we want to print only numbers which are major than 5

for el in array:
    if el>5:
        print(el)

6
7
8
9


In [ ]:
array = np.arange(0,10,1)

# we want to print only numbers which are major than 5

for el in array:
    if el>5:
        print(el)
    #from here we are out from the if indentation but we are still in the for indentation
    print('ciao')

In [40]:
array = np.arange(0,10)

# we want to print only numbers which are less or equal to 5


for el in array:
    if el<=5:
        print(el)

0
1
2
3
4
5


In [41]:
weights = [57,49,89,78,73,95,63,110,98,95] 
heights = [1.65,1.56,1.89,1.80,1.67,1.85,1.60,2.02,1.83,1.89] 

#the two list have the same lenght so we can cycle on their index to print the record

for i in range(len(weights)):
    BMI = weights[i]/heights[i]**2
   
    if BMI > 25:
        print('Patient',i+1,'weights',weights[i],'kg and is',heights[i],'m high and his BMI is',BMI)

Patient 5 weights 73 kg and is 1.67 m high and his BMI is 26.175194521137367
Patient 6 weights 95 kg and is 1.85 m high and his BMI is 27.757487216946675
Patient 8 weights 110 kg and is 2.02 m high and his BMI is 26.958141358690323
Patient 9 weights 98 kg and is 1.83 m high and his BMI is 29.26334020126011
Patient 10 weights 95 kg and is 1.89 m high and his BMI is 26.595000139973685
